### ISSUE TITLE
missing .h files

### ISSUE THREAD

**Issue by i164j9** [oilulio/Microcontroller_TCPIP_stack#13]
missing the following files for application.c
md5.h
sha1.h
sha256.h
ripemd160.h

**Comment by oilulio** [comment]
As the README says "You will either need the hash function files (sha1.h, sha1.c etc) from https://github.com/oilulio/Microcontroller-hashes in the same directory, connected by symbolic links, or to comment out the requirement for them."  They're not duplicated here for configuration control reasons.
